---
# tasks file for frontend
#- name: deploy haproxy
#  hosts: frontends
#  gather_facts: false # remove later! speeds up testing
#  become: true
- name: Make sure httpd service is running
  systemd:
    state: started
    name: httpd
- name: install HAProxy
  yum:
    name=haproxy state=latest
- name: enable HAProxy
  service:
    name: haproxy
    state: started
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
#  handlers:
#    - name: restart HAproxy
#      service:
#        name: haproxy
#        state: restarted
